### ISSUE TITLE
error in operation.rb

### ISSUE THREAD

**Issue by danubiapaiva** [trailblazer/trailblazer-operation#11]
Please, 

Has anyone seen this error? Windows 10 

RuntimeError: Could not execute command to start test server
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:734:in `start_test_server_in_background'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:152:in `start_test_server_in_background'
        from (irb):2
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'

**Comment by apotonick** [comment]
Without any exception stack trace, we can't help.
