### ISSUE TITLE
Error during merge of dry-container in Operation call

### ISSUE THREAD

**Issue by guzart** [trailblazer/trailblazer-operation#14]
I tried passing a dry-container into the Operation call method, however there is an error during a dry-container merge.

This is the [example](http://trailblazer.to/gems/operation/2.0/release_notes.html#dry-container) I tried to run:

```ruby
my_container = Dry::Container.new
my_container.register("user_repository", -> { Object })
Create.({}, my_container)["user_repository"] #=> Object
```

And this is the error am getting:

```ruby
 NoMethodError:
       undefined method `_container' for {"params"=>{:inspector_id=>1}}:Hash
     # ruby-2.3.3/gems/dry-container-0.6.0/lib/dry/container/mixin.rb:147:in `merge'
     # ruby-2.3.3/gems/trailblazer-operation-0.0.13/lib/trailblazer/operation/skill.rb:35:in `call'
```

It seems that [`Skill::Positional`](https://github.com/trailblazer/trailblazer-operation/blob/master/lib/trailblazer/operation/skill.rb#L35) is calling `Dry::Container#merge`, but Dry::Container#merge is expecting another container.

**Comment by apotonick** [comment]
Hi @guzart, a container has to be passed as 3rd+ argument!

I'm thinking about adding something like

```ruby
class Create < Trailblazer::Operation
  namespace "song"
```

And then you pass the container like 

```ruby
Create.(params, {}, container)
```

And dependencies will be looked up automatically namespaced, e.g. `container["song.contract.class"]`. What do you think?

**Comment by guzart** [comment]
Hey @apotonick, 

Passing the container as the third parameter works as expected, I totally missed that when looking at the source code, thanks!

To be honest I am just starting to discover the ruby world outside of Rails, and recently started to play with dry-rb and trailblazer, so am not sure how valuable my opinion is. 

I think `namespace` is a great idea to smooth the interop between Trailblazer macros and Dry-containers. But if it's a feature exclusively for loading dependencies from a container, personally I would prefer a more explicit name, like `container_namespace`.

**Comment by apotonick** [comment]
That's fine @guzart - I haven't played too much with containers so I would gladly appreciate you insights.

How do you use containers ATM? It's really important to collect input here! :beers:

**Comment by guzart** [comment]
Right now am just in an exploratory phase of dry-rb gems. The reason I was looking into containers was for dependency injection to replace the database access layer (repositories) with an in memory version for testing.

**Comment by apotonick** [comment]
I would love to elaborate together on this, since I'm really interested in integrating that properly, as I think containers are a great structural feature.

**Comment by guzart** [comment]
Sorry for the late reply, I was doing my research on dry-rb and trailblazer and we decided to build the app using Go 🙃

I would've love to collaborate on this too, but since am not working in Ruby-land anymore I don't think I'll be of much help, nevertheless keep up the great work mate!

**Comment by apotonick** [comment]
> doing my research on dry-rb and trailblazer and we decided to build the app using Go

Hahaha, I will always use this as a disclaimer now!

**Comment by guzart** [comment]
LOL 😂.... I didn't mean it like that, it wasn't consequential of dry-rb and trailblazer
