### ISSUE TITLE
`Rescue` macro

### ISSUE THREAD

**Issue by petrosp** [trailblazer/trailblazer-operation#19]
The documentation states that a [`Rescue` macro](http://trailblazer.to/gems/operation/2.0/api.html#rescue) is available, but when trying to call it, it returns `NoMethodError: undefined method 'Rescue' for ModifyPerson:Class`

Checking this gem's source, I can not really find any reference to it.

I am using Rails 4.2.9 and I have bundled only the `trailblazer-operation` gem not the whole suite.

What is the catch?

thanks...

**Comment by apotonick** [comment]
All macros come with the `trailblazer` gem.

**Comment by petrosp** [comment]
Yes indeed! Thanks, I am closing this if you don't mind...
