### ISSUE TITLE
Include operation class in results

### ISSUE THREAD

**Issue by dnd** [trailblazer/trailblazer-operation#3]
There is currently no way to know when looking at a `results` instance exactly what operation was executed. The value could be included in the hash, but is probably something that should also be included on the object as a first class piece of data. `Result#operation` maybe? 

The current preferred method to workaround this in every operation currently by a few users users on gitter right now is:

`step ->(options, **) {options[:operation] = self}`

**Comment by apotonick** [comment]
This is per design, the operation instance should in no way be exposed to the user, as it only represents implementation for steps. Otherwise, and we had that in TRB1, people will start adding decoration code and the like to the operation.

**Comment by dnd** [comment]
This was a typo mistake on my part. It should have read `step ->(options, **) {options[:operation] = self.class}` so that code looking at a result set can know what kind of operation was run.

I agree that it should not be necessary for the actual operation instance to be passed around. I don't even think there's anything useful you could do with that in a normal context.

**Comment by apotonick** [comment]
Ah, ok, good to know we agree on the throw-away instance!

Where would it be helpful to have the class, though? Is that for testing, only? We could provide that in the TRB testing code? But I need to understand how/where this is needed?

**Comment by dnd** [comment]
No, this is something I would use outside of testing code. Frequently after I call an operation the results might get sent through a number of generic methods afterwards before say a request is finalized. Some of that might be metrics, some just might be deciding how to interpret the results. I'm sure others have other uses of their own.

At the end of the day, I think it's fundamentally about what the results represent. If you look at them now as they stand they clearly represent "something", but without also passing along the operation class to other methods down the chain, there's no way to know what it represents. 

It is something the results are perfectly capable of and should be providing. They represent a specific something. What is that something?

**Comment by dnd** [comment]
Can we reopen this, given the clarification?
