### ISSUE TITLE
Error when trying to define Output for step

### ISSUE THREAD

**Issue by McRip** [trailblazer/trailblazer-operation#35]
```ruby
class Foo < Trailblazer::Operation
  step :foo
  step :bar, Output(:success) => :baz
  step :baz
end

Foo.call
=>
TypeError: no implicit conversion of nil into Hash
from trailblazer-activity-dsl-linear-0.1.6/lib/trailblazer/activity/dsl/linear/normalizer.rb:161:in `merge'
```

**Comment by McRip** [comment]
`
trailblazer-activity (0.8.3)
trailblazer-activity-dsl-linear (0.1.6)
trailblazer-context (0.1.4)
trailblazer-operation (0.5.2)
`

**Comment by McRip** [comment]
Works like this:

```ruby
class Foo < Trailblazer::Operation
    step :foo
    step :bar, Output(:success) => Id(:baz)
    step :baz
  end
```

The docs are different. http://trailblazer.to/2.1/trailblazer/wiring.html#decider.

**Comment by apotonick** [comment]
New docs are here: https://2019.trailblazer.to

**Comment by McRip** [comment]
Great, but `https://2019.trailblazer.to` gives me a cert error and redirects me to https://api.trailblazer.to/ where i have to login.

**Comment by apotonick** [comment]
@fernandes :scream:

**Comment by fernandes** [comment]
@McRip now it's ok, thanks for mentioning 😉

**Comment by panSarin** [comment]
I see that one is resolved so I am closing it.
