### ISSUE TITLE
Class Dependencies

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer-operation#38]
Does `extend Representer::DSL` etc work?

**Comment by yogeshjain999** [comment]
It was moved out from `trailblazer` in this commit `805a435`, but that isn't added back here. We can add such compact DSL methods back.

**Comment by apotonick** [comment]
I re-implemented it here: https://github.com/trailblazer/trailblazer-operation/tree/class-dependencies

**Comment by panSarin** [comment]
So we can close it @apotonick  ?
