### ISSUE TITLE
Include name of step that switched tracks in result

### ISSUE THREAD

**Issue by dnd** [trailblazer/trailblazer-operation#5]
`Result` doesn't currently provide the implementer with a way of knowing which step in an operation switched the track from success to failure. Including the name of the switching step in the results would help later code know where exactly where an operation failed, and allow it to act accordingly.

**Comment by apotonick** [comment]
Cool idea, but duplicate here: http://trailblazer.to/gems/operation/2.0/api.html#result-api :beers:
