### ISSUE TITLE
Accept non-falsey steps for failure

### ISSUE THREAD

**Issue by dnd** [trailblazer/trailblazer-operation#7]
Instead of just failing when a "falsey" value is received. Allow for a construct, or mechanism to fail steps with a non-falsey value that is then additionally retained as a "reason" for the failure. This failure can then additionally be provided on the returned results object.

https://gist.github.com/dnd/1b5955886584062b467d9ca88ac1e5bf

**Comment by panSarin** [comment]
Hey @dnd - that issue sounds to be outdated, also 2.1 was released - so I close it for now. Also, join us at zulipchat to discuss anything else that you want :) https://trailblazer.zulipchat.com/join/od4yhihn6tra3ix39u4gks72/

**Comment by apotonick** [comment]
This is actually possible now using a branching `Path()`. https://2019.trailblazer.to/2.1/docs/activity.html#activity-wiring-api-path-
