### ISSUE TITLE
Nested doesn't pass runtime data

### ISSUE THREAD

**Issue by KonstantinKo** [trailblazer/trailblazer-operation#8]
The following test case fails for me in trailblazer-operation version 0.0.9:

```ruby
class Inner < Trailblazer::Operation
  step :two

  def two(options)
    options['foo'] # expecting this to equal true but is nil
  end
end

class Outer < Trailblazer::Operation
  step :one
  step Nested(Inner)

  def one(options)
    options['foo'] = true
  end
end

Outer.().success?.must_equal(true) # (fails)
```

**Comment by georgemillo** [comment]
I had the same issue; turns out this behaviour is intentional. See https://github.com/trailblazer/trailblazer/issues/166

**Comment by apotonick** [comment]
It passes runtime data, but not mutable data. You can say what you want to "leak": http://trailblazer.to/gems/operation/2.0/api.html#nested-input

I'm fully open to "default patterns" here, though, when designing the API I decided it's better to be defensive. Please comment!
